import { Listing } from './types';

export const mockListings: Listing[] = [
  {
    id: '1',
    title: '80 CY Clean Fill Dirt – SE Calgary',
    category: 'Dirt & Aggregate',
    subcategory: 'Fill Dirt',
    listingType: 'For Sale',
    price: null,
    priceType: 'contact',
    sellerName: 'Prairie Excavating',
    sellerType: 'contractor',
    location: 'SE Calgary, AB',
    postalCode: 'T2H 1A1',
    distance: 3,
    postedTime: '2 hours ago',
    urgency: 'today',
    quantity: 80,
    unit: 'CY',
    description: 'Clean fill from subdivision excavation. Ready for immediate haul. Loader available for fast loadout.',
    availability: 'Available now - must move today',
    condition: 'excellent',
    additionalDetails: {
      materialType: 'clean_fill',
      loadingAvailable: true,
      dumpTruckAccess: true,
      contamination: 'Clean - tested',
      readyNow: true,
    },
  },
  {
    id: '2',
    title: '14 CY 32 MPa Concrete Remaining After 2 PM Pour',
    category: 'Concrete',
    subcategory: 'Leftover Concrete',
    listingType: 'For Sale',
    price: 45,
    priceType: 'fixed',
    sellerName: 'Ready Mix Supply Co.',
    sellerType: 'supplier',
    location: 'Downtown Calgary',
    postalCode: 'T2P 0X1',
    distance: 2,
    postedTime: '30 mins ago',
    urgency: 'urgent',
    quantity: 14,
    unit: 'CY',
    description: 'Leftover from morning pour. 32 MPa mix, good workability. Same day only. Truck available.',
    availability: 'Must pick up or pump by 6 PM',
    additionalDetails: {
      mixType: '32 MPa',
      deliveryWindow: 'Same day only',
      pumpRequired: false,
      shortLoad: true,
      deliveryAvailable: true,
    },
  },
  {
    id: '3',
    title: 'Used Symons Steel Forms – Good Condition',
    category: 'Materials',
    subcategory: 'Forming Systems',
    listingType: 'For Sale',
    price: 3500,
    priceType: 'negotiable',
    sellerName: 'Frame & Build Rentals',
    sellerType: 'supplier',
    location: 'NE Calgary',
    postalCode: 'T2A 0R6',
    distance: 8,
    postedTime: '4 hours ago',
    quantity: 120,
    unit: 'SF',
    description: 'Symons steel formwork. 120 SF total. Good condition, minor cosmetic wear. Complete set includes clamps, ties, hardware.',
    condition: 'good',
    availability: 'Available for immediate pickup',
    additionalDetails: {
      materialType: 'formwork',
      pickupOnly: true,
      condition: 'good',
      grade: 'Commercial',
    },
  },
  {
    id: '4',
    title: '3 Bundles #6 Rebar – Pickup Only',
    category: 'Materials',
    subcategory: 'Steel & Rebar',
    listingType: 'For Sale',
    price: 180,
    priceType: 'fixed',
    sellerName: 'Quality Steel Supply',
    sellerType: 'supplier',
    location: 'Southwest Calgary',
    postalCode: 'T3C 0N1',
    distance: 12,
    postedTime: '1 day ago',
    quantity: 3,
    unit: 'bundles',
    description: '3 bundles of #6 rebar, grade 400W. Left over from last project. Must pickup with your own truck.',
    condition: 'excellent',
    availability: 'Store hours 8 AM - 5 PM',
    additionalDetails: {
      materialType: 'rebar',
      grade: '400W',
      pickupOnly: true,
      deliveryAvailable: false,
    },
  },
  {
    id: '5',
    title: '3/4" Crushed Gravel Available by Loader Bucket',
    category: 'Dirt & Aggregate',
    subcategory: 'Gravel & Stone',
    listingType: 'For Sale',
    price: 45,
    priceType: 'fixed',
    sellerName: 'Westside Landscape Materials',
    sellerType: 'yard',
    location: 'West Calgary',
    postalCode: 'T3B 0M8',
    distance: 15,
    postedTime: '3 hours ago',
    quantity: 'Large stockpile',
    unit: 'per bucket',
    description: 'Fresh crushed 3/4" minus gravel. Great for drainage, driveway base, landscaping. Loader available for quick loadout.',
    availability: 'Available 7 AM - 5 PM daily',
    additionalDetails: {
      materialType: 'crushed_gravel',
      loadingAvailable: true,
      dumpTruckAccess: true,
    },
  },
  {
    id: '6',
    title: 'Skid Steer with Operator Available This Week',
    category: 'Equipment',
    subcategory: 'Heavy Equipment Rental',
    listingType: 'For Rent',
    price: 800,
    priceType: 'fixed',
    sellerName: 'ProRent Equipment',
    sellerType: 'owner_operator',
    location: 'Central Calgary',
    postalCode: 'T2E 0B6',
    distance: 5,
    postedTime: '6 hours ago',
    description: 'Bobcat S650 skid steer with certified operator. Great for site prep, material handling, grading. Available Mon-Fri.',
    availability: 'This week only',
    additionalDetails: {
      equipmentType: 'skid_steer',
      makeModel: 'Bobcat S650',
      pricing: 'daily',
      withOperator: true,
      deliveryAvailable: true,
      condition: 'excellent',
    },
  },
  {
    id: '7',
    title: 'Tri-Axle Dump Truck Hauling – Weekday Availability',
    category: 'Hauling',
    subcategory: 'Trucks & Trailers',
    listingType: 'Service Available',
    price: 120,
    priceType: 'fixed',
    sellerName: 'Fast Haul Services',
    sellerType: 'owner_operator',
    location: 'Southeast Calgary',
    postalCode: 'T2H 0E8',
    distance: 4,
    postedTime: '5 hours ago',
    description: 'Tri-axle dump truck ready for material hauls. Soil, gravel, demolition debris, clean fill. Fast turnaround, professional driver.',
    availability: 'Weekdays only, flexible scheduling',
    additionalDetails: {
      serviceType: 'dump_truck_hauling',
      truckType: 'tri_axle_dump',
      capacity: '25 tons',
      operatorIncluded: true,
      serviceRadius: '50 km',
      haulType: 'general_material',
      sameDay: true,
    },
  },
  {
    id: '8',
    title: 'Small Concrete Finishing Crew – 4 Man Crew',
    category: 'Labor & Crews',
    subcategory: 'Trades & Services',
    listingType: 'Service Available',
    price: 320,
    priceType: 'fixed',
    sellerName: 'Expert Finish Concrete',
    sellerType: 'crew',
    location: 'Calgary metro',
    postalCode: 'T2G 0A1',
    distance: 6,
    postedTime: '8 hours ago',
    urgency: 'this_week',
    description: 'Experienced 4-man concrete finishing crew. Troweling, broom finish, control joints, edge work. Fast and clean.',
    availability: 'Available this week',
    additionalDetails: {
      trade: 'concrete_finishing',
      crewSize: 4,
      certifications: ['Concrete Finishing'],
      minimumBooking: '1 day',
      insured: true,
      travelRadius: '50 km',
    },
  },
  {
    id: '9',
    title: '24 LF Steel Pipe Offcuts',
    category: 'Materials',
    subcategory: 'Steel & Metal',
    listingType: 'For Sale',
    price: 75,
    priceType: 'negotiable',
    sellerName: 'Metro Steel Fabrication',
    sellerType: 'contractor',
    location: 'Northeast Calgary',
    postalCode: 'T2K 5G6',
    distance: 10,
    postedTime: '2 days ago',
    quantity: 24,
    unit: 'LF',
    description: '3" Schedule 40 steel pipe offcuts from custom project. Good for scrap or reuse. Selling as lot.',
    condition: 'as_is',
    availability: 'Pickup anytime at shop',
    additionalDetails: {
      materialType: 'steel_pipe',
      grade: 'Schedule 40',
      pickupOnly: true,
    },
  },
  {
    id: '10',
    title: '40 Sheets 3/4" Plywood Forming Panels',
    category: 'Materials',
    subcategory: 'Lumber & Panels',
    listingType: 'For Sale',
    price: 400,
    priceType: 'fixed',
    sellerName: 'Builders Supply Depot',
    sellerType: 'supplier',
    location: 'South Calgary',
    postalCode: 'T2V 0J9',
    distance: 11,
    postedTime: '18 hours ago',
    quantity: 40,
    unit: 'sheets',
    description: '3/4" CDX plywood, 4x8 sheets. Minimal edge damage. Great for concrete forming. Bulk discount if you take all.',
    condition: 'good',
    availability: 'In stock, ready to load',
    additionalDetails: {
      materialType: 'plywood',
      grade: 'CDX',
      thickness: '3/4"',
      dimensions: '4x8',
      pickupOnly: false,
      deliveryAvailable: true,
    },
  },
  {
    id: '11',
    title: 'Mini Excavator for Rent – Delivery Available',
    category: 'Equipment',
    subcategory: 'Heavy Equipment Rental',
    listingType: 'For Rent',
    price: 250,
    priceType: 'fixed',
    sellerName: 'Equipment Plus Rentals',
    sellerType: 'supplier',
    location: 'Calgary South',
    postalCode: 'T2S 0B5',
    distance: 7,
    postedTime: '4 hours ago',
    description: '3.5 ton mini excavator. Thumb attachment included. Hedging, grading, material handling. Delivery available to jobsite.',
    availability: 'Daily rental rates',
    additionalDetails: {
      equipmentType: 'mini_excavator',
      weight: '3.5 tons',
      hourly: false,
      daily: true,
      withOperator: false,
      deliveryAvailable: true,
      condition: 'excellent',
    },
  },
  {
    id: '12',
    title: 'Wanted: Topsoil – 50+ CY Needed ASAP',
    category: 'Dirt & Aggregate',
    subcategory: 'Topsoil',
    listingType: 'Wanted',
    price: null,
    priceType: 'contact',
    sellerName: 'GreenSpace Landscaping',
    sellerType: 'contractor',
    location: 'West Calgary',
    postalCode: 'T3A 0V5',
    distance: 9,
    postedTime: '1 hour ago',
    urgency: 'urgent',
    quantity: 50,
    unit: 'CY',
    description: 'Looking for quality topsoil for landscape restoration project. Need 50+ CY. Must be clean and weed-free. Quick turnaround needed.',
    availability: 'Need ASAP - this week',
    additionalDetails: {
      materialType: 'topsoil',
      deliveryNeeded: true,
      quantityMinimum: 50,
    },
  },
  {
    id: '13',
    title: 'Wanted: Demolition Labor Today – Quick Demo Job',
    category: 'Labor & Crews',
    subcategory: 'Trades & Services',
    listingType: 'Service Needed',
    price: 200,
    priceType: 'negotiable',
    sellerName: 'Fast Build Contractors',
    sellerType: 'contractor',
    location: 'Downtown Calgary',
    postalCode: 'T2P 0Z9',
    distance: 2,
    postedTime: '30 mins ago',
    urgency: 'today',
    description: 'Need 2-3 strong demolition workers for today. Interior drywall, flooring, framing removal. Full day work, starts 8 AM.',
    availability: 'Today only - starting 8 AM',
    additionalDetails: {
      trade: 'demolition',
      crewSize: '2-3 workers',
      minimumBooking: '1 day',
      sameDay: true,
    },
  },
  {
    id: '14',
    title: '50 Bags Type 10 Cement – Wholesale Price',
    category: 'Materials',
    subcategory: 'Concrete Materials',
    listingType: 'For Sale',
    price: 250,
    priceType: 'fixed',
    sellerName: 'Concrete Supply Plus',
    sellerType: 'supplier',
    location: 'Northeast Calgary',
    postalCode: 'T2E 8B8',
    distance: 13,
    postedTime: '12 hours ago',
    quantity: 50,
    unit: 'bags',
    description: 'Bulk lot of 50 bags Type 10 Portland cement. Slightly overstocked, passing savings to contractors. Free delivery over $200.',
    condition: 'excellent',
    availability: 'In stock - quick shipping',
    additionalDetails: {
      materialType: 'cement',
      type: 'Type 10',
      packaging: 'bags',
      deliveryAvailable: true,
    },
  },
  {
    id: '15',
    title: 'Flatbed Trailer for Lease – Weekly Rate',
    category: 'Equipment',
    subcategory: 'Heavy Equipment Rental',
    listingType: 'For Rent',
    price: 400,
    priceType: 'fixed',
    sellerName: 'Mobile Equipment Services',
    sellerType: 'owner_operator',
    location: 'East Calgary',
    postalCode: 'T2Z 0C3',
    distance: 6,
    postedTime: '1 day ago',
    description: '25-ton gooseneck flatbed trailer, well-maintained. Great for hauling equipment, materials, or machinery.',
    availability: 'Available - weekly rates',
    additionalDetails: {
      equipmentType: 'flatbed_trailer',
      capacity: '25 tons',
      pricing: 'weekly',
      deliveryAvailable: false,
      condition: 'good',
    },
  },
  {
    id: '16',
    title: 'Framing Crew Available – 3 Carpenters',
    category: 'Labor & Crews',
    subcategory: 'Trades & Services',
    listingType: 'Service Available',
    price: 145,
    priceType: 'fixed',
    sellerName: 'Solid Frame Construction',
    sellerType: 'crew',
    location: 'Calgary',
    postalCode: 'T2L 0V1',
    distance: 8,
    postedTime: '2 hours ago',
    urgency: 'this_week',
    description: '3-carpenter framing crew. Wall framing, roof trusses, deck building. Fast, clean work. 20+ years combined experience.',
    availability: 'Available this week',
    additionalDetails: {
      trade: 'framing',
      crewSize: 3,
      certifications: ['Carpentry'],
      minimumBooking: '3 days',
      insured: true,
      travelRadius: '60 km',
      unionStatus: 'non_union',
    },
  },
  {
    id: '17',
    title: 'Wanted: Used Formwork – Any Condition',
    category: 'Materials',
    subcategory: 'Forming Systems',
    listingType: 'Wanted',
    price: null,
    priceType: 'contact',
    sellerName: 'Budget Build Services',
    sellerType: 'contractor',
    location: 'South Calgary',
    postalCode: 'T2H 0Y8',
    distance: 4,
    postedTime: '18 hours ago',
    description: 'Looking to buy used concrete formwork - plywood, steel forms, adjustable props, anything. Any condition considered. Must be bulk lot.',
    availability: 'Quick pickup available',
    additionalDetails: {
      materialType: 'formwork',
      conditionFlexible: true,
    },
  },
  {
    id: '18',
    title: 'Excavator with Operator – Site Prep Work',
    category: 'Equipment',
    subcategory: 'Heavy Equipment Rental',
    listingType: 'Service Available',
    price: 150,
    priceType: 'fixed',
    sellerName: 'Pro Excavating Solutions',
    sellerType: 'owner_operator',
    location: 'Calgary',
    postalCode: 'T2A 1Z5',
    distance: 7,
    postedTime: '3 hours ago',
    urgency: 'this_week',
    description: '320D excavator with experienced operator. Grading, trenching, site preparation, material handling. Efficient and professional.',
    availability: 'Available this week',
    additionalDetails: {
      equipmentType: 'large_excavator',
      makeModel: 'CAT 320D',
      pricing: 'hourly',
      withOperator: true,
      deliveryAvailable: true,
      condition: 'excellent',
      minimumHours: 4,
    },
  },
  {
    id: '19',
    title: '10 Pallets Mixed Concrete Pavers – Overstock',
    category: 'Materials',
    subcategory: 'Hardscape Materials',
    listingType: 'For Sale',
    price: 600,
    priceType: 'negotiable',
    sellerName: 'StoneWorks Supplier',
    sellerType: 'supplier',
    location: 'Northwest Calgary',
    postalCode: 'T3B 5S7',
    distance: 14,
    postedTime: '1 day ago',
    quantity: 10,
    unit: 'pallets',
    description: 'Overstock of concrete pavers - mix of colors and sizes. Good quality, slight imperfections on some. Bulk discount on full load.',
    condition: 'good',
    availability: 'Ready to load now',
    additionalDetails: {
      materialType: 'concrete_pavers',
      palletized: true,
      deliveryAvailable: true,
    },
  },
];

export const mockCategories = [
  'Materials',
  'Dirt & Aggregate',
  'Concrete',
  'Equipment',
  'Hauling',
  'Labor & Crews',
];

export const mockSubcategories: Record<string, string[]> = {
  Materials: [
    'Steel & Rebar',
    'Lumber & Panels',
    'Steel & Metal',
    'Concrete Materials',
    'Forming Systems',
    'Hardscape Materials',
  ],
  'Dirt & Aggregate': [
    'Fill Dirt',
    'Topsoil',
    'Gravel & Stone',
    'Sand',
    'Crushed Rock',
    'Spoil & Mixed Fill',
  ],
  Concrete: [
    'Ready Mix Concrete',
    'Leftover Concrete',
    'Concrete Products',
  ],
  Equipment: [
    'Heavy Equipment Rental',
    'Trucks & Trailers',
    'Tools & Compaction',
    'Pumping Equipment',
    'Aerial Work Platforms',
  ],
  Hauling: [
    'Trucks & Trailers',
    'Dump Truck Hauling',
    'Specialized Hauling',
    'Material Transportation',
  ],
  'Labor & Crews': [
    'Trades & Services',
    'Excavation & Grading',
    'Concrete Work',
    'Framing & Carpentry',
    'Heavy Equipment Operation',
  ],
};
